# Generated by Django 5.2.3 on 2025-07-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('resolved', 'Resuelto'), ('close', 'Cerrado'), ('cancel', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
