# Generated by Django 5.2.3 on 2025-07-03 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='submissionDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
