# Generated by Django 5.2.3 on 2025-07-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ticket_submissiondate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='service',
        ),
        migrations.AlterField(
            model_name='dataticket',
            name='info',
            field=models.TextField(),
        ),
    ]
